accountapp/urls.py
# accountapp/urls.py

from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
# from . import views

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

# 127.0.0.1:8000/account/

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),  # 함수형 뷰는 이름을 넣음

    path('login/', LoginView.as_view(template_name="accountapp/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('create/', AccountCreateView.as_view(), name='create'),    # 클래스형 뷰는 as_view() 추가
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    # 127.0.0.1/8000
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),
]

accountapp/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

articleapp/models.py
# articleapp/models.py

from django.contrib.auth.models import User
from django.db import models

from projectapp.models import Project


# Create your models here.

class Article(models.Model):
    # user가 회원탈퇴 시, 알수없음으로 나타나게
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)     # save in /media/article
    content = models.TextField(null=True)
    created_at = models.DateField(auto_now_add=True, null=True)

accountapp/forms.py
'''
update에서 아이디 비활성화를 위하여 views.py의
AccountUpdateView의 form_class 상속받아 수정
'''

from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
# accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from articleapp.models import Article

has_ownership = [account_ownership_required, login_required]

@login_required # if login, do func. Or go to login
def hello_world(request):

    if request.method == "POST":

        temp = request.POST.get('hello_world_input')    # html에서 받은 hello_world_input을 받음

        new_hello_world = HelloWorld()
        new_hello_world.text = temp
        new_hello_world.save()         # DB에 저장

        return HttpResponseRedirect(reverse('accountapp:hello_world'))
        # return redirect('accountapp:hello_world')
    else:
        hello_world_list = HelloWorld.objects.all()
        return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})



# Create view
class AccountCreateView(CreateView):    # class based view. 장고에서 user 관련하여 지원해줌
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world') # 어느 경로로 다시 재배정    class는 reverse_lazy 사용
    template_name = 'accountapp/create.html'

# Read view
class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

    paginate_by = 25

    # 어떠한 게시글을 가지고 올 것인지 작성. get_context_data는 장고에서 제공해줌, --> template에서 object_list 사용
    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())  # writer의 모든 object를 가져옴
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)

# Update view
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'


# Delete view
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

# method_decorator는 def에서 사용하는 decorator를 class에서도 사용할 수 있도록 해줌
'''
@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
@method_decorator(account_ownership_required, 'get')
@method_decorator(account_ownership_required, 'post')

==
has_ownership = [account_ownership_required, login_required]
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
'''

accountapp/templates/accountapp/create.html
{# accountapp/create.html #}
{% extends 'base.html' %}
{% load bootstrap4 %} {# pip install django-bootstrap4 #}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4">
            <h4> SignUp</h4>
        </div>
        {# 기존 action="/account/create" 에서 일원화를 위해 '앱이름:url이름(라우팅)'으로 작성 #}
        <form action="{% url 'accountapp:create' %}" method="post">
            {% csrf_token %}
            {# views.py/AccountCreateView/form_class에 있는 form을 자동으로 읽음 #}
            {# {{ form }}#}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>

    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{# accountapp/delete.html #}
{% extends 'base.html' %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4">
            <h4> Quit</h4>
        </div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>

    </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{# accountapp/detail.html #}
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto">
            <p>
                {{ target_user.date_joined }}
            </p>



            {% if target_user.profile %}
                <img src="{{ target_user.profile.image.url }}" alt=""
                     style="height: 20rem; width: 20rem; border-radius: 10rem; margin-bottom: 2rem; object-fit: cover;">

                <h2 style="font-family: 'NanumSquareB'">
                    {{ target_user.profile.nickname }}
                    {% if target_user == user %}
                        <a class="material-icons"
                           style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;"
                                {# 0 0 4px : 그림자 위치, 그림자 크기, 색 #}
                           href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                            edit
                        </a>
                    {% endif %}
                </h2>
                <h5 style="margin-bottom: 3rem; font-family: 'NanumSquareB'">
                    {{ target_user.profile.message }}
                </h5>

            {% else %}
                {% if target_user == user %}
                    <a href="{% url 'profileapp:create' %}">
                        <h2 style="font-family: 'NanumSquareB'">
                            Create Profile
                        </h2>
                    </a>
                {% else %}
                    <h2>
                        No Profile
                    </h2>
                {% endif %}
            {% endif %}

            {% if target_user == user %}
                <a class="material-icons"
                   style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: .4rem;"
                   href="{% url 'accountapp:update' pk=user.pk %}">
                    settings
                </a>
                <a class="material-icons"
                   style="box-shadow: 0 0 4px #fcc; border-radius: 10rem; padding: .4rem;"
                   href="{% url 'accountapp:delete' pk=user.pk %}">
                    cancel
                </a>
            {% endif %}
        </div>

        <div>
            {% include 'snippets/list_fragment.html' with article_list=object_list %}
        </div>

    </div>


{% endblock %}

accountapp/templates/accountapp/hello_world.html
{# accountapp/helloworld.html #}
{% extends 'base.html' %}

{% block content %}

    <div style="border-radius: 1rem; margin: 2rem; text-align: center;">
        <h1 style="font-family: 'Playfair Display', cursive;">
            Hello World LIST!
        </h1>

        {# 데이터 명세서 : 해당 주소로 post를 사용하여 요청을 보냄 -> 그를 위한 interaction button #}
{#        <form action="/account/hello_world/" method="post">#}
        <form action="{% url 'accountapp:hello_world' %}" method="post">
            {# csrf_token를 form 안에 명시해야함 : 보안기능 #}
            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input">
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>
        </form>
        {#  hello_world_output이 있다면 실행  #}
        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
            <h4>
                {{ hello_world.text }}
            </h4>
            {% endfor %}
        {% endif %}

    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{# accountapp/login.html #}

{% extends 'base.html' %}
{% load bootstrap4 %} {# pip install django-bootstrap4 #}
{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
{#                 {{ form }}#}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>

    </div>


{% endblock %}

{#input class #}
{# col-6은 부모창의 50% --> col-12는 100% #}
{# mt == margin top #}

accountapp/templates/accountapp/update.html
{# accountapp/create.html #}
{% extends 'base.html' %}
{% load bootstrap4 %} {# pip install django-bootstrap4 #}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4">
            <h4> Change Info</h4>
        </div>
        {# 기존 action="/account/create" 에서 일원화를 위해 '앱이름:url이름(라우팅)'으로 작성 #}
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
            {% csrf_token %}
            {# views.py/AccountCreateView/form_class에 있는 form을 자동으로 읽음 #}
{#            {{ form }}#}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>

    </div>

{% endblock %}