articleapp/urls.py
# articleapp/urls.py

from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = "articleapp"

# 127.0.0.1:8000/article/

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),

    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(template_name='articleapp/detail.html'), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(template_name='articleapp/update.html'), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(template_name='articleapp/delete.html'), name='delete'),
]

pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    # 127.0.0.1/8000
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/models.py
# articleapp/models.py

from django.contrib.auth.models import User
from django.db import models

from projectapp.models import Project


# Create your models here.

class Article(models.Model):
    # user가 회원탈퇴 시, 알수없음으로 나타나게
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)     # save in /media/article
    content = models.TextField(null=True)
    created_at = models.DateField(auto_now_add=True, null=True)

templates/snippets/card.html
{# article 레이아웃을 바꾸는 곳 #}
<div>
    <img src="{{ article.image.url }}" alt="">
</div>

templates/snippets/card_project.html
{# pragmatic/templates/snippets/card_project.html #}
{# project 레이아웃을 바꾸는 곳 #}
<div style="display: block; text-align: center;">
    <img src="{{ project.image.url }}" alt="">
    <h5 class="mt-2" style="font-family: 'NanumSquareB';">
        {{ project.title | truncatechars:8 }}   {# 글자 길이 ...로 변환 #}
    </h5>

</div>

templates/snippets/list_fragment.html
{# templates/snippets/list_fragment.html #}

{% load static %}


<style>

    .container {
        padding: 0;
        margin: 0 auto;
    }

    {#  container 안에 들어있는 a태그 수정  #}
    .container a {
        width: 40%;
        max-width: 250px;
    }

    .container div {
    {#width: 250px;#}{#height: 500px;#} display: flex;
        justify-content: center;
        align-items: center;
        border-radius: 1rem;
    }

    .container img {
        width: 100%;
        border-radius: 1rem;
    }

</style>
{% if article_list %}
    <div class="container">

        {% for article in article_list %}
            <a href="{% url 'articleapp:detail' pk=article.pk %}">
                {% include 'snippets/card.html' with article=article %} {# article이 snippets 안에 있는 article과 동일하다 #}
            </a>
        {% endfor %}
    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script>
{% else %}
    <div style="text-align: center;">
        <h1>No Article YET!</h1>
    </div>
{% endif %}

{% include 'snippets/pagination.html' with page_obj=page_obj %}

<div style="text-align: center; ">
    <a href="{% url 'articleapp:create' %}" class="btn btn-dark rounded-pill mt-3 mb-3 px-3">
        Create Article
    </a>
</div>

templates/snippets/pagination.html
<div style="text-align: center; margin: 1rem 0;">
    {#  has_previous현재 페이지에서 이전 페이지가 있는지 확인하는 물리형 객체  #}
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"
        class="btn btn-secondary rounded-pill">
        {{ page_obj.previous_page_number }}
    </a>
    {% endif %}
    {# 현재페이지를 향하는 링크 #}
    <a href="?page={{ page_obj.number }}"
        class="btn btn-secondary rounded-pill active">
        {{ page_obj.number }}
    </a>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}"
        class="btn btn-secondary rounded-pill">
        {{ page_obj.next_page_number }}
    </a>
    {% endif %}
</div>
{#<a href="{% url 'articleapp:list' %}?page={{ page_obj.next_page_number }}"#}