pragmatic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    # 127.0.0.1/8000
    path('', ArticleListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
# projectapp/urls.py

from django.urls import path

from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView

app_name = "projectapp"

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
]

subscribeapp/urls.py
# subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

articleapp/models.py
# articleapp/models.py

from django.contrib.auth.models import User
from django.db import models

from projectapp.models import Project


# Create your models here.

class Article(models.Model):
    # user가 회원탈퇴 시, 알수없음으로 나타나게
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)     # save in /media/article
    content = models.TextField(null=True)
    created_at = models.DateField(auto_now_add=True, null=True)

projectapp/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    image = models.ImageField(upload_to='project/', null=False)
    title = models.CharField(max_length=20, null=False)
    description = models.CharField(max_length=200, null=True)

    created_at = models.DateTimeField(auto_now=True)

    # Project_object(1) 라는 이름을 번호와 제목으로 표현 (article/create에서 확인)
    def __str__(self):
        return f'{self.pk} : {self.title}'

projectapp/forms.py
# projectapp/forms.py

from django.forms import ModelForm

from projectapp.models import Project


class ProjectCreationForm(ModelForm):
    class Meta:
        model = Project
        fields = ['image', 'title', 'description']

projectapp/views.py
# projectapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, DetailView
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from projectapp.forms import ProjectCreationForm
from projectapp.models import Project
from subscribeapp.models import Subscription


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectCreationForm
    template_name = 'projectapp/create.html'

    def get_success_url(self):
        return reverse('projectapp:detail', kwargs={'pk': self.object.pk})


# MultipleObjectMixin : 여러가지 object를 다룰 수 있도록 함
class ProjectDetailView(DetailView, MultipleObjectMixin):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/detail.html'

    paginate_by = 25

    # 어떠한 게시글을 가지고 올 것인지 작성. get_context_data는 장고에서 제공해줌, --> template에서 object_list 사용
    def get_context_data(self, **kwargs):
        project = self.object
        user = self.request.user
        # login 하고 있다면 구독하고 있는지 확인해서 Template에 넘김
        if user.is_authenticated:
            subscription = Subscription.objects.filter(user=user, project=project)
        else:
            subscription = None
        object_list = Article.objects.filter(project=self.get_object())
        return super(ProjectDetailView, self).get_context_data(object_list=object_list,
                                                               subscription=subscription,
                                                               **kwargs)   # template으로 가는 정보


class ProjectListView(ListView):
    model = Project
    context_object_name = 'project_list'
    template_name = 'projectapp/list.html'
    paginate_by = 25

projectapp/templates/projectapp/create.html
{# projectapp/create.html #}
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4">
            <h4> Create Project</h4>
        </div>
        <form action="{% url 'projectapp:create' %}" method="post" enctype="multipart/form-data"> {# image가 들어가므로 #}
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

projectapp/templates/projectapp/detail.html
{# projectapp/detail.html #}
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto 1.5rem auto;">

            <img src="{{ target_project.image.url }}" alt=""
                 style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem; object-fit: cover;">
            <h2 style="font-family: 'NanumSquareB'">
                {{ target_project.title }}
            </h2>
            <h5>
                {{ target_project.description }}
            </h5>
        </div>

        <div class="text-center mb-5">
            {% if user.is_authenticated %}
                {% if not subscription %}
                    {# subscribeapp/view.py에서 GET방식으로 project_pk 데이터를 넘겨줌  #}
                    <a href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}"
                       class="btn btn-primary rounded-pill px-4">
                        Subscribe
                    </a>
                {% else %}
                    <a href="{% url 'subscribeapp:subscribe' %}?project_pk={{ target_project.pk }}"
                       class="btn btn-dark rounded-pill px-4">
                        Unsubscribe
                    </a>
                {% endif %}
            {% endif %}
        </div>

        <div>
            {% include 'snippets/list_fragment.html' with article_list=object_list %}
        </div>
    </div>
{% endblock %}

projectapp/templates/projectapp/list.html
{# projectapp/list.html #}

{% extends 'base.html' %}
{% load static %}

{% block content %}

    <style>

        .container {
            padding: 0;
            margin: 0 auto;
        }

        .container div {
            display: flex;
            justify-content: center;
            align-items: center;

            border-radius: 1rem;
        }

        .container img {
            width: 7rem;
            height: 7rem;
            object-fit: cover;  {# image 원본 비율로 자름 #}
            border-radius: 1rem;
        }

    </style>
    {% if project_list %}
        <div class="container">
            {% for project in project_list %}
                <a href="{% url 'projectapp:detail' pk=project.pk %}">
                    {% include 'snippets/card_project.html' with project=project %} {# article이 snippets 안에 있는 article과 동일하다 #}
                </a>
            {% endfor %}
        </div>
        <script src="{% static 'js/magicgrid.js' %}"></script>
    {% else %}
        <div style="text-align: center;">
            <h1>No Project YET!</h1>
        </div>
    {% endif %}

    {% include 'snippets/pagination.html' with page_obj=page_obj %}

    <div style="text-align: center; ">
        <a href="{% url 'projectapp:create' %}" class="btn btn-dark rounded-pill mt-3 mb-3 px-3">
            Create Project
        </a>
    </div>

{% endblock %}